# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sent_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
